# Generated by Django 2.1.4 on 2020-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=40, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=40, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_id', models.CharField(max_length=40)),
                ('photo', models.FileField(upload_to='documents/')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=40, null=True)),
                ('complaint_type', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cmp_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=40)),
                ('regno', models.CharField(max_length=40)),
                ('doc_name', models.CharField(max_length=40)),
                ('request_date', models.DateField()),
                ('user_id', models.CharField(max_length=40)),
                ('verify_status', models.CharField(max_length=100)),
                ('acceptance_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Download_Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=40)),
                ('doc_name', models.CharField(max_length=40)),
                ('download_date', models.DateField()),
                ('download_time', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Forword_Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_id', models.CharField(max_length=40)),
                ('staff_name', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=40)),
                ('forword_date', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Forword_complaints_workes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_id', models.CharField(max_length=40)),
                ('forword_date', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Security_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('security_key', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=40)),
                ('user_id', models.CharField(max_length=40)),
                ('regno', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=40)),
                ('document_name', models.CharField(max_length=40)),
                ('upload_doc', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Registration1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('utype', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
