# Generated by Django 2.1.4 on 2020-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_docs',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
